### PR TITLE
Codingunicorn hitchhiker galaxy design

### PR DESCRIPTION
**Pull request by codingunicorn**
**Changes:**

- use green, slightly opaque Don't Panic Slogan as defined in the Design
- use Galaxy Background also as the Background of the other Pages

**see preview:**

bildschirmfoto 2018-08-14 um 16 58 16
bildschirmfoto 2018-08-14 um 16 58 45

### CODE REVIEW

**Comment by codingunicorn** [comment]
Hey Lukas,
We can do that, we'd just lose even more quality... How much exactly would you like to go down with the image size? Then I can try to further compress it or change the size accordingly.

For the padding, I totally agree. For the button size, I would like to make all a bit larger, but I'll make you a suggestion, so that the top button is still more noticeable. Thank you.

**Comment by codingunicorn** [comment]
Hey Lukas, 
I now updated the padding size of the buttons now, so the button looks like this: 


grafik

I kindly ask you to merge this already.

**Comment by ChristofBuechi** [comment]
@lukaselmer please have a look on this change

**Comment by ChristofBuechi** [comment]
aligned branch with actual developer

**Pull request merged**
