### PR TITLE
Feature/team page

### PR DESCRIPTION
**Pull request by ChristofBuechi**
extend Teampage with needed details. I assume, more small updates will come from the teammembers, but as of today, it looks complete. I was able to build it locally, but the new data was not shown. :( Any step beside gulp serve needed to integrate initial-data.json ?

### CODE REVIEW

**Comment by lukaselmer** [comment]
Very nice, thx!

> I was able to build it locally, but the new data was not shown. :( Any step beside gulp serve needed to integrate initial-data.json?

It's not very well documented, sorry. To update the data, we need to import it into the firebase database (https://github.com/gdgzh/devfest18-website/blob/develop/docs/tutorials/firebase.md, step 5) :wink:

**Comment by lukaselmer** [comment]
@ChristofBuechi i just noticed that the image of Jacques is not square, and thus looks a bit funny:
image
Can you fix that? And maybe also check that the other images are square 😉 thx

**Comment by rac2030** [comment]
Maybe have a look into https://github.com/urish/firebase-server for local
testing. Haven't done it but others had that issue as well

**Comment by lukaselmer** [comment]
> I just asked for another picture :)
Great, thx!

> the rest of the pictures is not shown, but they should be okay.
Yeah, that's one of the drawbacks of PWA: it's not easy to get right, and along the way, the template creators made a mistake... The main issue is that the app caches stuff, and does not update on it's own. I just hope that the people visiting the site don't have the content of last year still on their computer 🙄

The other images are fine 👍 
image

To refresh, you can clear the site data (button "clear site data"):
image

> just for understanding: A local preview-deployment is then not possible, since there is just one source of truth which is called firebase?
Yes and no. You can set the api key here https://github.com/gdgzh/devfest18-website/blob/develop/data/hoverboard.config.json#L22 😉 Until now it didn't matter, so i just used the master database, and always overwrote all the data with our data:
image

If you want to test stuff, you can do that too until we are live. From then on, i suggest that we use https://console.firebase.google.com/u/0/project/devfest18ch-develop/database/devfest18ch-develop/data or even https://console.firebase.google.com/u/0/project/devfest18ch-development/database/devfest18ch-development/data for local testing 😄 or https://github.com/urish/firebase-server as suggested by @rac2030

**Comment by lukaselmer** [comment]
and we also have to define if we want to continue changing the json file, or at some point, modify the data in the database 😉 i'm open for both

**Pull request merged**
